In [4]:
amount=int(input("enter the amount="))
dict={}
l=[2000,500,200,100,50,20,10,5,2,1]
for i in l:
    if amount>=i:
        q=amount//i
        amount=amount-q*i
        dict[i]=q
for j in dict:
    print("Rs",j,"=",dict[j])
    
        

enter the amount=9826
Rs 2000 = 4
Rs 500 = 3
Rs 200 = 1
Rs 100 = 1
Rs 20 = 1
Rs 5 = 1
Rs 1 = 1


In [23]:
passd=input("enter password=")
en=""
de=""
for ch in passd:
    en=en+chr(ord(ch)+3)
for j in en:
    de=de+chr(ord(j)-3)
print("encrpyted password =",en)
print("decrpyted password=",de)


enter password=praveen1555@.pk
encrpyted password = sudyhhq4888C1sn
decrpyted password= praveen1555@.pk


In [25]:
cel=int(input("enter temperature="))
farh=9/5*cel+32
kel=cel+273
print(cel,"celsius","=",farh,"fahrenheit","=",kel,"kelvin")

enter temperature=35
35 celsius = 95.0 fahrenheit = 308 kelvin


In [8]:
sub=['CS','CO&A','FLAG','DBMS','OOPS','SL']
sum=0
dict={}
k={'CS':3.0,'CO&A':3.0,'FLAG':3.0,'DBMS':3.0,'OOPS':3.0,'SL':3.0}
for i in sub:
    dict[i]=int(input(i))
    grade=(dict[i]//10)+1
    sum=sum+((grade*k[i])/k[i])
cgpa=sum/6
print("CGPA=",cgpa)
    

CS98
CO&A88
FLAG78
DBMS98
OOPS95
SL94
CGPA= 9.5


In [ ]:
sen=input("enter sentence=")
word=input("enter word to search=")
sum=0
wl=len(word)
for ch in range(len(sen)-len(word)+1):
    if word==sen[ch:wl]:
        sum=sum+1 
    wl=wl+1
print("the word",word.upper(),"=",sum)




In [9]:
num=int(input("enter numerator="))
den=int(input("enter denominator="))
q=num//den
r=num%den
print("mixed fraction=",q,r,"/",den)

enter numerator=3
enter denominator=2
mixed fraction= 1 1 / 2


In [27]:
l=[]
k=[]
m=[]
for i in range(3):
    for j in range(3):
        k.append(int(input("enter number=")))
    l.append(k)
    k=[]
    for p in range(3):
        k.append(int(input("enter number for 2=")))
    m.append(k)
    k=[]
for i in range(3):
    print(l[i],m[i],sep="\t")
temp=[]
add=[]
for i in range(3):
    for j in range(3):
        temp.append(l[i][j]+m[i][j])
    add.append(temp)
    temp=[]
print("\n")
for i in range(3):
    print(add[i])
        

enter number=1
enter number=2
enter number=3
enter number for 2=4
enter number for 2=5
enter number for 2=6
enter number=4
enter number=5
enter number=6
enter number for 2=7
enter number for 2=8
enter number for 2=9
enter number=1
enter number=2
enter number=3
enter number for 2=4
enter number for 2=5
enter number for 2=6
[1, 2, 3]	[4, 5, 6]
[4, 5, 6]	[7, 8, 9]
[1, 2, 3]	[4, 5, 6]


[5, 7, 9]
[11, 13, 15]
[5, 7, 9]
[[5, 7, 9], [11, 13, 15], [5, 7, 9]]


In [1]:
import numpy as np
l=list(map(int,input("enter number=").split(" ")))
k=list(map(int,input("enter number=").split(" ")))
l=np.array(l).reshape(3,3)
k=np.array(k).reshape(3,3)
print("first matrix","second matrix",sep="\t")
for i in range(3):
    print(l[i],k[i],sep="\t\t")
add=np.add(l,k)
sub=np.subtract(l,k)
mul=np.matmul(l,k)
print("addition",add,"subtraction",sub,"multiplication",mul,sep="\n")




    

enter number=1 2 3 4 5 6 7 8 9
enter number=1 2 3 4 5 6 7 8 9
first matrix	second matrix
[1 2 3]		[1 2 3]
[4 5 6]		[4 5 6]
[7 8 9]		[7 8 9]
addition
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
subtraction
[[0 0 0]
 [0 0 0]
 [0 0 0]]
multiplication
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [69]:
import pandas as pd
pk=pd.DataFrame({"Name":["praveen","rahaman","balaji","Yuvi","Avinash"],
                "RollNo":[60,42,16,36,20],
                "year":[2,2,3,4,3]})
pk.index=[1,2,3,4,5]
print(pk)
pk.loc[len(pk)]=["ok",22,2]

      Name  RollNo  year
1  praveen      60     2
2  rahaman      42     2
3   balaji      16     3
4     Yuvi      36     4
5  Avinash      20     3


Name  RollNo  year
1  praveen      60     2
2  rahaman      42     2
3   balaji      16     3
4     Yuvi      36     4
5       ok      22     2

In [ ]:
##pandas
##Series
##DataFrame##loc[]->to get specfied row
##read_csv()->to load the CSV file
##to_string()->to get full df
##head()
##tail()
##pd.dropna()->removes rows contains null   If you want to change the original DataFrame, use the inplace = True argument:
##The fillna() method allows us to replace empty cells with a value: df.fillna(130, inplace = True)
## row adding->df.append(df2,ignore_index=True)(or)df.loc[len(df)]=['values',..]
##merge->pd.merge(df1,df2, on="common columnname")

In [76]:
import pandas as pd
df = pd.read_csv('data.csv')
print(df.columns)
print(df["Calories"].max())
l=[]
for i in df.columns:
    l.append(df[i].mean())
print(l)
df.loc[len(df)]=l

    


Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')
1860.4
[63.84615384615385, 107.46153846153847, 134.0473372781065, 375.79024390243916]
